Repository kids-first/clovoc-app-fhir-ingest, pull requests merged in 2022-05, with the labels that each got.

#3 Add Data Files
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/.gitkeep
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/hypospadiasFamilyHistory.tsv
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/hypospadiasGeneralObservations.tsv
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/hypospadiasMetabolomeFileManifest.tsv
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/hypospadiasParticipantDetails.tsv
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/hypospadiasPhenotype.tsv
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/hypospadiasSpecimen.tsv
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/hypospadiasTreatmentHistory.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/.gitkeep
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/vurFamilyHistory.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/vurGeneralObservations.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/vurMetabolomeFileManifest.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/vurParticipantDetails.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/vurPhenotype.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/vurSpecimen.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/vurTreatmentHistory.tsv
Labels: feature

#4 🐛 Fix Participant Details
  .gitignore
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/hypospadiasParticipantDetails.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/vurParticipantDetails.tsv
Labels: bug

#5 🐛 Fix General Observations
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/hypospadiasGeneralObservations.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/vurGeneralObservations.tsv
Labels: bug

#6 🐛 Fix Participant Phenotypes
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/hypospadiasParticipantPhenotypes.tsv
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/hypospadiasPhenotype.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/vurParticipantPhenotypes.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/vurPhenotype.tsv
Labels: bug

#7 ✨ Extract Clinical Data
  .gitignore
  kf_ingest_packages/packages/CLOVoc/data/clinical.tsv
  kf_ingest_packages/packages/CLOVoc/extract_configs/extract_config.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/hypospadias_general_observations.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/hypospadias_participant_details.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/hypospadias_participant_phenotypes.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/vur_general_observations.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/vur_participant_details.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/vur_participant_phenotypes.py
Labels: feature

#8 🚚 Rename Files
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/BiospecimenCollectionManifest.tsv
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/FamilyHistory.tsv
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/GeneralObservations.tsv
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/MetabolomeFileManifest.tsv
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/ParticipantDetails.tsv
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/ParticipantPhenotypes.tsv
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/TreatmentHistory.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/BiospecimenCollectionManifest.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/FamilyHistory.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/GeneralObservations.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/MetabolomeFileManifest.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/ParticipantDetails.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/ParticipantPhenotypes.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/TreatmentHistory.tsv
  kf_ingest_packages/packages/CLOVoc/extract_configs/hypospadias_general_observations.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/hypospadias_participant_details.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/hypospadias_participant_phenotypes.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/vur_general_observations.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/vur_participant_details.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/vur_participant_phenotypes.py
Labels: feature

#9 🐛 Fix Biospecimen Collection Manifest
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/BiospecimenCollectionManifest.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/BiospecimenCollectionManifest.tsv
Labels: bug

#10 ✨ Extract Specimen Data
  kf_ingest_packages/packages/CLOVoc/extract_configs/hypospadias_biospecimen_collection_manifest.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/vur_biospecimen_collection_manifest.py
Labels: feature

#13 ✨ Load Data
  config.py
  kf_ingest_packages/packages/CLOVoc/data/hypospadias/BiospecimenCollectionManifest.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/BiospecimenCollectionManifest.tsv
  kf_ingest_packages/packages/CLOVoc/data/vesico-ureteric-reflux/GeneralObservations.tsv
  kf_ingest_packages/packages/CLOVoc/extract_configs/hypospadias_biospecimen_collection_manifest.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/hypospadias_general_observations.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/vur_biospecimen_collection_manifest.py
  kf_ingest_packages/packages/CLOVoc/extract_configs/vur_general_observations.py
  kf_ingest_packages/packages/CLOVoc/ingest_package_config.py
  requirements.txt
  setup.py
  target_api_plugins/clovoc_api_fhir_service.py
  target_api_plugins/entity_builders/__init__.py
  target_api_plugins/entity_builders/document_reference.py
  target_api_plugins/entity_builders/group.py
  target_api_plugins/entity_builders/patient.py
  target_api_plugins/entity_builders/phenotype.py
  target_api_plugins/entity_builders/practitioner.py
  target_api_plugins/entity_builders/research_study.py
  target_api_plugins/entity_builders/research_subject.py
  target_api_plugins/entity_builders/specimen.py
  target_api_plugins/entity_builders/vital_signs.py
  target_api_plugins/utils.py
Labels: bug, feature
